# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4449a86a4cd092df64602a10b9f5d114"
name = "Rush order"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
