api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "demo-cart-transform-extension"
type = "function"
uid = "5aafc664-1fb3-e40d-bc86-3f1a94931a54b0776bb4"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/run.graphql"
  export = "cart_transform_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/demo-cart-transform-extension.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
